amplify-devops-testing:
  account_id: "714402078798"
  log_level: DEBUG
  ec2_table: flappy-detector-ec2-state
  max_event_age_in_mins: 120
  min_num_events: 5
  min_spread: 1

  enable_dd_asm: true
amplify-devops:
  # Must quote, otherwise leading 0 is stripped
  account_id: "023225265359"
  log_level: INFO
  ec2_table: flappy-detector-ec2-state
  max_event_age_in_mins: 120
  min_num_events: 5
  min_spread: 1
